POST http://localhost:8080/download
Content-Type: application/json

{
  "location": "",
  "file_name": "go.txt"
}

###

GET http://localhost:8080/download/chunk?id=0
Accept: text/plain

###
GET http://localhost:8080/download/chunk?id=2
Accept: text/plain

###

