POST http://localhost:8080//upload
Content-Type: application/json

{
  "location": "",
  "file_name": "test.txt",
  "chunks_num": 3
}

###

POST http://localhost:8080//upload/chunk?id=1
Content-Type: text/plain

dont

###

POST http://localhost:8080//upload/chunk?id=2
Content-Type: text/plain

letme

###

POST http://localhost:8080//upload/completed
Content-Type: text/plain



###

POST http://localhost:8080//upload/chunk?id=0
Content-Type: text/plain

go

###

