POST http://localhost:8080/cd
Content-Type: application/json

{
  "path": "new"
}

###

POST http://localhost:8080/mkdir
Content-Type: application/json

{
  "path": "",
  "dirname": "wearegonnabevictorious.txt"
}

###

POST http://localhost:8080/copy
Content-Type: application/json

{
  "src_dir_path": "",
  "file_name": "test_dir",
  "dest_dir_path": "wearegonnabevictorious"
}

###


