# @no-cookie-jar
POST http://localhost:8080/cd
Content-Type: application/json

{
  "path": "new"
}

###

POST http://localhost:8080/mkdir
Content-Type: application/json

{
  "path": "",
  "dir_name": "wearegonnabevictorious.txt"
}

###

POST http://localhost:8080/copy
Content-Type: application/json

{
  "src_dir_path": "",
  "file_name": "test_dir",
  "dest_dir_path": "wearegonnabevictorious"
}

###

POST http://localhost:8080/authenticate
Content-Type: application/json

{
  "name": "goga",
  "password": "qwerty"
}

