POST http://localhost:8080/cd
Content-Type: application/json

{
  "path": "test_dir"
}

###
POST http://localhost:8080/mkdir
Content-Type: application/json

{
  "path": "",
  "dir_name": "diggydiggyhole"
}

###
POST http://localhost:8080/ls
Content-Type: application/json

{
  "path": ""
}

###

